branches:
  only:
  - main
language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: yarn install --frozen-lockfile && yarn run deploy
  skip_cleanup: true
  on:
    branch: main