name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.15.1
      uses: actions/setup-node@v2
      with:
        node-version: 10.15.1
    - run: npm install -g gatsby-cli
    - run: git config --global user.email "iqan@iqans.com"
    - run: git config --global user.name "Iqan Shaikh"
    - run: yarn install && yarn run deploy
